name: Build Docker Container & Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Build web container image
        run: |
          docker build -f Dockerfile \
            -t roychew3/tf-python:latest \
            -t roychew13/tf-python:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push container
        run: |
           docker push roychew13/tf-python --all-tags
